cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
#    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name= 'apply'),
]

orders/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

probiotics/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders') ),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('products/',include('products.urls',  namespace='products')),
    path('users', include('users.urls', namespace='users')),
    path('', views.home, name='home' ),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    

coupons/forms.py
from django import forms 

class CouponApplyForm(forms.Form):
    code = forms.CharField()
    

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm



# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_update(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)



@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Shopping Cart{% endblock %} 

{% block body%}

    <hr class="offset-md">

    <div class="box">
      <div class="container">
          <h1>Your Shopping Cart</h1>
          <hr class="offset-sm">
      </div>
    </div>
    <hr class="offset-md">


    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <div class="checkout-cart">
                      <div class="content">
                        {% for item in cart %}
                            {% with product=item.product%}
                          <div class="media">
                            <div class="media-left">
                              {% comment %} <a href="{{ product.get_absolute_url }}">
                                <img class="media-object" src="{{ product.image.url }}" alt="{{ product.slug }}"/>
                              </a> {% endcomment %}
                              {% if product.image %}
    <img class="media-object" src="{{ product.image.url }}" alt="{{ product.slug }}" />
{% else %}
    {% comment %} <p>No Image Available</p> {% endcomment %}
{% endif %}

                            </div>
                            <div class="media-body">
                              <h2 class="h4 media-heading">{{ product.title }}</h2>
                              <label>{{ product.category }}</label>
                              <p class="price">Ksh.{{ item.price }}</p>
                            </div>
                            <div class="controls">
                              <div class="input-group">
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                  {% csrf_token %}
                                  {{ item.update_quantity_form.quantity }}
                                  {{ item.update_quantity_form.override }}
                                  <button class="btn btn-default btn-sm"><i class="ion-ios-cart"></i> Update</button>
                                  
                                </form>                  
                                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                  <!-- <input class="btn btn-default btn-sm" type="submit" value="Remove"><i class="ion-trash-b"></i> -->
                                  <button class="btn btn-default btn-sm"><i class="ion-trash-b"></i> Remove</button>
                                  {% csrf_token %}
                                </form>              
                              </div><!-- /input-group -->
                            </div>
                          </div>
                            {% endwith %}
                        {% endfor %}
                        
                      </div>
                    </div>
                  </div>
                </div>
            </div>
            <div class="col-sm-8 col-md-4">
              <hr class="offset-md visible-sm">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <h2 class="no-margin">Summary</h2>
                    <hr class="offset-md">

                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-6">
                                {% with total_items=cart|length %}
                                  {% if total_items > 0 %}
                                    <p>Total Items:
                                      {{ total_items }} item{{ total_items|pluralize }}
                                    </p> 
                                  {% else %}
                                    <p>Your Cart is Empty</p>
                                  {% endif %}
                                {% endwith %}
                            </div>
                            <div class="col-xs-6">
                                <p><b> Ksh.{{ cart.get_total_price }}</b></p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <form action="{% url "coupons:apply" %}" method="post">
                      {% csrf_token %}
                    <div class="checkboxes">
                      <div class="radio">
                          <label for='id_code'>
                              <!-- <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked> -->
                              Coupon
                          </label>
                          <hr class="offset-xs">
  
                          <div class="input-group">
                              <input id="id_code" type="text" class="form-control input-sm" name="code" placeholder="Insert code">
                              <span class="input-group-btn">
                              <button class="btn btn-primary btn-sm" type="submit">Apply</button>
                              </span>
                          </div><!-- /input-group -->
                          <hr class="offset-sm">
                      </div>
                      <!-- <div class="radio">
                          <label>
                          <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                          Coupon
                          </label>
                      </div> -->
                  </div>
                  </form>
                    <div class="container-fluid">
                        <div class="row">
                          {% if cart.coupon %}
                          <div class="col-xs-6">
                            <h3 class="no-margin">Code: </h3>
                            <h3 class="no-margin">Discount: </h3>
                            <h3 class="no-margin">Total sum: </h3>
                          </div>
                          <div class="col-xs-6">
                            <h3 class="no-margin">'{{ cart.coupon.code }}' </h3>
                            <h3 class="no-margin">{{ cart.coupon.discount }}% </h3>
                            {% endif %}
                            <h3 class="no-margin">$ {{ cart.get_total_price_after_discount|floatformat:3 }}</h3>
                          </div>
                         
                        </div>
                    </div>
                    <hr class="offset-md">

                    <a href="{% url 'orders:order_create' %}" class="btn btn-primary btn-lg justify"><i class="ion-android-checkbox-outline"></i>&nbsp;&nbsp; Checkout order</a>
                    <hr class="offset-md">

                    <p>Pay your order in the most convenient way</p>
                    <div class="payment-icons">
                      <img src="{% static 'img/payments/icon-paypal.svg' %}" alt="paypal">
                      <img src="{% static 'img/payments/icon-visa.svg' %}" alt="visa">
                      <img src="{% static 'img/payments/icon-mc.svg' %}" alt="mc">
                      <img src="{% static 'img/payments/icon-discover.svg' %}" alt="discover">
                      <img src="{% static 'img/payments/icon-ae.svg' %}" alt="ae">
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <hr class="offset-lg">
    <hr class="offset-lg">



{% endblock body%}