cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
#    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

probiotics/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders') ),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('products/',include('products.urls',  namespace='products')),
    path('users', include('users.urls', namespace='users')),
    path('', views.home, name='home' ),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path

from . import views


app_name = 'products'

urlpatterns = [

    path('catalog/', views.CatalogView.as_view(), name='products_catalog'),
    path('recom/', views.recom_list_view, name='recom_products'),
    path('gallery/', views.GalleryView.as_view(), name='products_gallery'),
    path('products/', views.product_list_view, name='products_list'),
    path('tag/<slug:tag_slug>/', views.product_list_view, name='product_list_by_tag'),
    path('filter/<slug:cat_filter>/', views.product_list_view, name="product_list_by_filter"),
    path('filter_by_manufacturer/<slug:manu_filter>/', views.product_list_view, name="product_list_by_manufacturer_filter"),
    path('filter_by_name_ascend/<slug:name_ascend>/', views.product_list_view, name="products_list_by_name_ascend"),
    path('filter_by_name_descend/<slug:name_descend>/', views.product_list_view, name="products_list_by_name_descend"),
    path('filter_by_price_ascend/<slug:price_ascend>/', views.product_list_view, name="products_list_by_price_ascend"),
    path('filter_by_price_descend/<slug:price_descend>/', views.product_list_view, name="products_list_by_price_descend"),
    path('products/<int:id>/<slug:slug>/', views.product_detail_view, name="product_list_detail"),
    path('<slug:slug>/', views.ProductDetailSlugView.as_view()),
]

products/models.py
from django.db import models
import random
import os
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.forms import widgets

from taggit.managers import TaggableManager

from .utils import unique_slug_generator

# Create your models here.


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1,4739628451)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename, 
            final_filename=final_filename
            )

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)
    
    def search(self, query):
        lookups = (Q(title__icontains=query) | 
                  Q(description__icontains=query) |
                  Q(price__icontains=query) | 
                  Q(category__icontains=query))

        return self.filter(lookups).distinct()
    
    def category_filter(self, query):
        return self.filter(category=query)
    
    def manufacturer_filter(self, query):
        return self.filter(manufacturer=query)

        
class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self): #Product.objects.featured() 
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id) # Product.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)

    def category_filter(self, query):
        return self.filter(category=query)

    def manufacturer_filter(self, query):
        return self.filter(manufacturer=query)



Men= 'Men'
Women = 'Women'
Kids = 'Kids'

Nestle = 'Nestle'
Culturelle= 'Culturelle'
Solaray= 'Solaray'
InnovixLabs = 'Innovix Labs'
MegaFood= 'MegaFood'

class Product(models.Model):
    # Category Choices
    CATEGORY = (
        (Men, 'Men'),
        (Women, 'Women'),
        (Kids, 'Kids'),
    )

    MANUFACTURER = (
        (Nestle, 'Nestle'),
        (Culturelle, 'Culturelle'),
        (Solaray, 'Solaray'),
        (InnovixLabs, 'InnovixLabs'),
        (MegaFood, 'Megafood'),

    )

    title           = models.CharField(max_length=120)
    slug            = models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2, max_digits=20, default=2000.00)
    image           = models.ImageField(upload_to='product_images/', null=True, blank=True)
    featured        = models.BooleanField(default=False)
    active          = models.BooleanField(default=True)
    category        = models.CharField(max_length=150, choices=CATEGORY , default= Men)
    manufacturer    = models.CharField(max_length=150, choices=MANUFACTURER, default= Nestle )
    updated_on      = models.DateField(auto_now_add=True, null=True)
    created_on      = models.DateField(auto_now_add=True, null=True)
    tags            = TaggableManager()    

    objects = ProductManager()

    # class Meta:
    #     app_label = 'apps.products'

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return "{id}/{slug}/".format(id=self.id,slug=self.slug)

    def get_related_products_by_tags(self):
        return Product.objects.filter(tags__in=self.tags.all())

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title



def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

products/views.py
from django.db.models import Count
from django.http import request, Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage

from collections import Counter

from taggit.models import Tag

from .models import Product
from cart.forms import CartAddProductForm

# Create your views here.


def home(request):
    template = 'home.html'
    cart_product_form = CartAddProductForm()
    queryset = Product.objects.all().order_by('-created_on').active()

    context = {
        'object_list': queryset,
        'cart_product_form': cart_product_form,
    }
    return render(request, template, context)


def contact(request):
    template = 'contact.html'
    return render(request, template)

def faq(request):
    template = 'faq.html'
    return render(request, template)

class CatalogView(TemplateView):
    template_name = 'products/catalog.html'

class GalleryView(TemplateView):
    template_name = 'products/gallery.html'


class ProductFeaturedListView(ListView):
    template_name = 'products/gallery.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()



class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all().featured()
    template_name = "products/featured-detail.html"


def product_list_view(request, cat_filter=None, name_ascend=None, name_descend=None, price_ascend=None, price_descend=None, manu_filter=None, tag_slug=None):
    queryset = Product.objects.all().order_by('-created_on')
    cart_product_form = CartAddProductForm()
    tagv = [] 
    for all_tags in queryset:
        for each_tag in all_tags.tags.order_by('name'):
            tagv.append(each_tag)
    uniq =  Counter(tagv)


    cat_filters = Product.objects.values_list('category', flat='true')
    cat_filt = []
    for cat in cat_filters:
        cat_filt.append(cat)
    filt = Counter(cat_filt)

    manu_filters = Product.objects.values_list('manufacturer', flat='true')
    manu_filt = []
    for manu in manu_filters:
        manu_filt.append(manu)
    manufacturer = Counter(manu_filt)

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        queryset = queryset.filter(tags__name__in=[tag]).distinct()

    if cat_filter:
        queryset = queryset.category_filter(cat_filter)
    # print(manu_filter)
    # queryset = queryset.manufacturer_filter('Samsung')
    # print("manu queries", queryset)

    if manu_filter:
        queryset = queryset.manufacturer_filter(manu_filter)
        print("manu queries", queryset)

    if name_ascend:
        queryset = queryset.order_by('title')

    if name_descend:
        queryset = queryset.order_by('-title')

    if price_ascend:
        queryset = queryset.order_by('price')
        
    if price_descend:
        queryset = queryset.order_by('-price')

    paginator = Paginator(queryset, 9)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    
    context = {
        'object_list': queryset,
        'cart_product_form': cart_product_form,
        'tag': tag,
        'page': page,
        'uniq': uniq,
        'filt': filt,
        'manufacturer': manufacturer

    }
    return render(request, "products/list.html", context)


def recom_list_view(request):
    queryset = Product.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "products/recommendation.html", context)



class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"
    cart_product_form = CartAddProductForm()

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        #instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Uhhmmm ")
        return instance


def product_detail_view(request, slug, *args, **kwargs):
    queryset = Product.objects.all()
    cart_product_form = CartAddProductForm()
    instance = get_object_or_404(Product, slug=slug, active=True)
    if instance is None:
        raise Http404("Product doesn't exist")
    similar_products = instance.tags.similar_objects()[:2]
    
    context = {
        'object': instance,
        'object_list': queryset,
        'cart_product_form': cart_product_form,
        'similar_products': similar_products,
        
    }
    return render(request, "products/detail.html", context)

class SearchProductView(ListView):
    template_name = "search/view.html"

    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        # SearchQuery.objects.create(query=query)
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q', None) # method_dict['q']
        if query is not None:
            return Product.objects.search(query)
        return Product.objects.featured()
        '''
        __icontains = field contains this
        __iexact = fields is exactly this
        '''

templates/products/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ object.title }} {% endblock %} 

{% block body%}

    <hr class="offset-lg">

    <div class="product">
    	<div class="container">
        <div class="row">
          <div class="col-sm-7 col-md-7">
            <div class="carousel product" data-count="5" data-current="1">
              <!-- <button class="btn btn-control"></button> -->

              <div class="items">
                <div class="item active" data-marker="1">
                {% if object.image %}
                    <img src="{{ object.image.url }}" alt="{{ object.title }}" />
                {% endif %}
                </div>
                <div class="item" data-marker="2">
                {% if object.image %}
                    <img src="{{ object.image.url }}" alt="{{ object.title }}" />
                {% endif %}
                </div>
                <div class="item" data-marker="3">
                {% if object.image %}
                    <img src="{{ object.image.url }}" alt="{{ object.title }}" />
                {% endif %}
                </div>
                <div class="item" data-marker="4">
                {% if object.image %}
                    <img src="{{ object.image.url }}" alt="{{ object.title }}" />
                {% endif %}
                </div>
                <div class="item" data-marker="5">
                {% if object.image %}
                    <img src="{{ object.image.url }}" alt="{{ object.title }}" />
                {% endif %}
                </div>
                <div class="item" data-marker="6">
                  <div class="tiles">
                    <a href="#video" data-gallery="#video" data-source="youtube" data-id="hED0N4CFoqs" data-title="An upscale new Chromebook from HP" data-description="{{ object.description }}">
                      {% if object.image %}
                        <img src="{{ object.image.url }}" alt="{{ object.title }}" />
                      {% endif %}

                      <div class="overlay"></div>
                      <div class="content">
                        <div class="content-outside">
                          <div class="content-inside">
                            <i class="ion-ios-play"></i>
                            <h1>Watch video review</h1>
                          </div>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              </div>

              <ul class="markers">
                <li data-marker="1" class="active"><img src="../assets/img/product/1.jpg" alt="Background"/></li>
                <li data-marker="2"><img src="../assets/img/product/2.jpg" alt="Background"/></li>
                <li data-marker="3"><img src="../assets/img/product/3.jpg" alt="Background"/></li>
                <li data-marker="4"><img src="../assets/img/product/4.jpg" alt="Background"/></li>
                <li data-marker="5"><img src="../assets/img/product/5.jpg" alt="Background"/></li>
                <li data-marker="6"><img src="../assets/img/product/video.jpg" alt="Background"/></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-5 col-md-5">
            {% if object.image %}
            <img src="{{ object.image.url }}" alt="HP" class="brand hidden-xs" />
            {% endif %}
            
            <h1>{{ object.title }}</h1>

            <p> &middot; {{ object.operating_system }}™</p>
            <p> &middot; {{ object.processor }}1920 1280</p>
            <p> &middot; {{ object.graphics }}</p>
            <p> &middot; {{ object.tags.all|join:", " }}</p>

            <p class="price">Ksh.{{object.price}}</p>
            <p class="price through">Ksh.3500.00</p>
            <br><br>
            <form action="{% url 'cart:cart_add' product_id=object.id %}" method="post">
              {% csrf_token %}
              {{ cart_product_form }}
              <input class="btn btn-primary btn-rounded btn-sm" type="submit" value="Add to Cart">
            </form>
            <!-- <button class="btn btn-primary btn-rounded"> <i class="ion-bag"></i> Add to cart</button> -->
          </div>
        </div>
    		<br><br><br>


	    	<div class="row">
	    		<div class="col-sm-7">
	    			<h1>{{ object.title }}</h1>
		    		 <br>

		    		 <p>
		    		 	{{ object.description }}
		    		 </p>
		    		 <br>

             <h2>Product specifications</h2>
             <br>

             <div class="row specification">
              <div class="col-sm-6"> <label>Manufacturer</label> </div>
              <div class="col-sm-6"> <p>{{ object.manufacturer}}™</p> </div>
            </div>

             
          </div>
          <div class="col-sm-5">
            <div class="comments">
              <h2 class="h3">What do you think? (#3)</h2>
              <br>


              <div class="wrapper">
                <div class="content">
                  <h3>Anne Hathaway</h3>
                  <label>2 years ago</label>
                  <p>
                    Apple Music brings iTunes music streaming to the UK. But is it worth paying for? In our Apple Music review, we examine the service's features, UK pricing, audio quality and music library
                  </p>


                  <h3>Chris Hemsworth</h3>
                  <label>Today</label>
                  <p>
                    Samsung's Galaxy S7 smartphone is getting serious hype. Here's what it does better than Apple's iPhone 6s.
                  </p>


                  <h3>Anne Hathaway</h3>
                  <label>2 years ago</label>
                  <p>
                    Apple Music brings iTunes music streaming to the UK. But is it worth paying for? In our Apple Music review, we examine the service's features, UK pricing, audio quality and music library
                  </p>
                </div>
              </div>
              <br>

              <button class="btn btn-default btn-sm" data-toggle="modal" data-target="#Modal-Comment"> <i class="ion-chatbox-working"></i> Add comment </button>
            </div>
            <br><br>

            <div class="talk">
              <h2 class="h3">Do you have any questions?</h2>
              <p>Online chat with our manager</p>

              <button class="btn btn-default btn-sm"> <i class="ion-android-contact"></i> Lat's talk </button>
            </div>
	    		</div>
	    	</div>
    	</div>
    </div>
    <br><br>
                <!-- {% block sidebar %}
                {% include 'products/recommendation.html' %}
                <p>___________________________________________</p>
                {% endblock sidebar %} -->

    <section class="products">
        <div class="container">
            <h1 class="h3">Recommendation for you.</h1>
            
            <div class="row">
              {% for sim in similar_products %} 
              <div class="col-sm-6 col-md-3 product">
                <a href="#favorites" class="favorites" data-favorite="inactive"><i class="ion-ios-heart-outline"></i></a>
                <a href="{% url 'products:product_list_detail' sim.id sim.slug %}"><img src="{{ sim.image.url }}" alt="HP {{ sim.slug }}"/></a>

                <div class="content">
                  <h1 class="h4">{{ sim.title }}</h1> 
                  <p class="price">Ksh. {{sim.price}}</p>
                  <label>{{ sim.category }}</label>
                  <a href="{% url 'products:product_list_detail' sim.id sim.slug %}" class="btn btn-link"> Details</a>
                  <!-- <button class="btn btn-primary btn-rounded btn-sm"> <i class="ion-bag"></i> Add to cart</button> -->
                  <form action="{% url 'cart:cart_add' sim.id %}" method="post">
                  {% csrf_token %}
                  {{ cart_product_form }}
                  <input class="btn btn-primary btn-rounded btn-sm" type="submit" value="Add to Cart">
                </form>
                </div>
              </div>
              {% endfor %}
            </div>
        </div>
    </section>
    <br><br>

{% endblock body%}

templates/products/featured-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Featured Detail {% endblock %} 

{% block body%}

{{ object.title }} <br/>
{{ object.description }} <br/>
{% if object.image %}
    <img src='{{ object.image.url }}' class='img-fluid' />

{% endif %}
{% endblock body%}

templates/products/list.html
 {% extends 'base.html' %}
{% load static %}

{% block title %} List Item {% endblock %} 

{% block body%}


    <hr class="offset-lg">

    <div class="container tags">
        <div class="btn-group pull-right">
          <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ion-arrow-down-b"></i> Sorting by name
          </button>
          <ul class="dropdown-menu">
            <li class="active"><a href="{% url 'products:products_list_by_name_ascend' True %}"> <i class="ion-arrow-down-c"></i> Name [A-Z]</a></li>
            <li><a href="{% url 'products:products_list_by_name_descend' True %}"> <i class="ion-arrow-up-c"></i> Name [Z-A]</a></li>
            <li><a href="{% url 'products:products_list_by_price_ascend' True %}"> <i class="ion-arrow-down-c"></i> Price [Low-High]</a></li>
            <li><a href="{% url 'products:products_list_by_price_descend' True %}"> <i class="ion-arrow-up-c"></i> Price [High-Low]</a></li>
          </ul>
        </div>
        <p>Search by tags</p>
        <div class="btn-group" >
          <label class="btn btn-default btn-xs active">
            <a href="{% url 'products:products_list' %}">All Products</a>
          </label>
          
          {% for u in uniq %}
          {% comment %} <label {% if request.path == '/business/' %}class="btn btn-default btn-xs active"{% endif %}> {% endcomment %}
            <label class="btn btn-default btn-xs">
            <a href="{% url 'products:product_list_by_tag' u|lower %}">{{ u }}</a> 
          </label>          
          {% if not forloop.last %} {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="container">
      <div class="row">
        <!-- Filter -->
        <div class="col-sm-3 filter">
          <div class="item">
              <div class="title">
                  <a href="#clear" data-action="open" class="down"> <i class="ion-android-arrow-dropdown"></i> Open</a>
                  <a href="#clear" data-action="clear"> <i class="ion-ios-trash-outline"></i> Clear</a>
                  <h1 class="h4">Type</h1>
              </div>
              <div class="controls">
                {% for cat in filt %}
                <div class="checkbox-group" data-status="inactive">
                  {% if cat in request.get_full_path%}
                  &nbsp;&nbsp;&nbsp;<i class="ion-android-done"></i>
                  {% else %}
                  {% endif %}                
                  <div class="label" data-value="{{ cat }}">
                    &nbsp;&nbsp; <a href="{% url 'products:product_list_by_filter' cat %}">{{ cat }}</a> 
                  </div>
                </div>
                {% endfor %}
              </div>
          </div>
          <br>

          <div class="item">
              <div class="title">
                  <a href="#clear" data-action="open" class="down"> <i class="ion-android-arrow-dropdown"></i> Open</a>
                  <a href="#clear" data-action="clear"> <i class="ion-ios-trash-outline"></i> Clear</a>
                  <h1 class="h4">Screen</h1>
              </div>

              <div class="controls grid">
                <div class="checkbox-group" data-status="inactive">
                    <div class="checkbox"><i class="ion-android-done"></i></div>
                    <div class="label" data-value="7 in">7 in</div>
                    <input type="checkbox" name="checkbox" value="">
                </div>

                <div class="checkbox-group" data-status="inactive">
                    <div class="checkbox"><i class="ion-android-done"></i></div>
                    <div class="label" data-value="10 in">10 in</div>
                    <input type="checkbox" name="checkbox" value="">
                </div>

                <div class="checkbox-group" data-status="inactive">
                    <div class="checkbox"><i class="ion-android-done"></i></div>
                     <div class="label" data-value="11 in">11 in</div>
                    <input type="checkbox" name="checkbox" value="">
                </div>

                <div class="checkbox-group" data-status="inactive">
                    <div class="checkbox"><i class="ion-android-done"></i></div>
                    <div class="label" data-value="14 in">14 in</div>
                    <input type="checkbox" name="checkbox" value="">
                </div>

                <div class="checkbox-group" data-status="inactive">
                    <div class="checkbox"><i class="ion-android-done"></i></div>
                    <div class="label" data-value="15 in">15 in</div>
                    <input type="checkbox" name="checkbox" value="">
                </div>

                <div class="checkbox-group" data-status="inactive">
                    <div class="checkbox"><i class="ion-android-done"></i></div>
                     <div class="label" data-value="17 in">17 in</div>
                    <input type="checkbox" name="checkbox" value="">
                </div>
              </div>
          </div>

          <br>

          <div class="item">
            <div class="title">
                <a href="#clear" data-action="open" class="down"> <i class="ion-android-arrow-dropdown"></i> Open</a>
                <a href="#clear" data-action="clear-price"> <i class="ion-ios-trash-outline"></i> Clear</a>
                <h1 class="h4">Price</h1>
            </div>

            <div class="controls">
                <br>
                <div id="slider-price"></div>
                <input type="text" name="min_price" maxlength="4" size="3" >
                <br>
                <p id="amount"></p>
            </div>
          </div>
          <br>

          <div class="item lite">
              <div class="title">
                  <a href="#clear" data-action="open" class="down"> <i class="ion-android-arrow-dropdown"></i> Open</a>
                  <a href="#clear" data-action="clear"> <i class="ion-ios-trash-outline"></i> Clear</a>
                  <h1 class="h4">Manufacturer</h1>
              </div>
              
              

              <div class="controls">
                {% for manu in manufacturer %}
              <div class="checkbox-group" data-status="inactive">
                {% if manu in request.get_full_path%}
                &nbsp;&nbsp;&nbsp;<i class="ion-android-done"></i>
                {% else %}
                {% endif %}                
                {% comment %} <div class="label" data-value="{{ manu }}">
                  &nbsp;&nbsp; <a href="{% url 'products:product_list_by_manufacturer_filter' manu %}">{{ manu }}</a> 
                </div> {% endcomment %}
              </div>
              {% endfor %}

              </div>
          </div>
        </div>
        <!-- /// -->

        <!-- Products -->
        {% comment %} <div class="col-sm-9 products">
          <div class="row">
            {% for obj in object_list %}
            <div class="col-sm-6 col-md-4 product">
              <a href="#favorites" class="favorites" data-favorite="inactive"><i class="ion-ios-heart-outline"></i></a>
              <a href='{{ obj.get_absolute_url }}'> <img src="{{ obj.image.url }}" alt="{{ obj.slug }}"/></a>
    
              <div class="content">
                <h1 class="h4">{{ obj.title }}</h1>
                <p class="price">${{ obj.price }}</p>
                <label>{{obj.category}}</label>

                <!-- <button class="btn btn-primary btn-rounded btn-sm"> <i class="ion-bag"></i> Add to cart</button> -->
                <form action="{% url 'cart:cart_add' obj.id %}" method="post">
                  {% csrf_token %}
                  {{ cart_product_form }}
                  
                  <input class="btn btn-primary btn-rounded btn-sm" type="submit" value="Add to Cart">
                </form>
                
              </div>
            </div>
            {% endfor %}
         {% endcomment %}
         {% for obj in object_list %}
<div class="col-sm-6 col-md-4 product">
    <a href="#favorites" class="favorites" data-favorite="inactive"><i class="ion-ios-heart-outline"></i></a>
    {% comment %} <a href='{{ obj.get_absolute_url }}'> <img src="{{ obj.image.url }}" alt="{{ obj.slug }}"/></a> {% endcomment %}
    <a href="{{ obj.get_absolute_url }}">
      {% if obj.image %}
          <img src="{{ obj.image.url }}" alt="{{ obj.slug }}" />
      {% else %}
          {% comment %} <p>No Image Available</p> {% endcomment %}
      {% endif %}
  </a>
  
    <div class="content">
        <h1 class="h4">{{ obj.title }}</h1>
        <p class="price">Ksh.{{ obj.price }}</p>
        <label>{{ obj.category }}</label>

        <form action="{% url 'cart:cart_add' obj.id %}" method="post">
            {% csrf_token %}
            {{ cart_product_form }}
            <input class="btn btn-primary btn-rounded btn-sm" type="submit" value="Add to Cart">
        </form>
    </div>
</div>
{% endfor %}

           
            <!-- Included Pagination -->
            
            <nav>            
                <ul class="pagination">
                  <li>
                    {% if object_list.has_previous %}
                    <a href="?page={{ object_list.previous_page_number }}" aria-label="Previous">
                      <span aria-hidden="true">Previous <i class="ion-ios-arrow-left"></i></span>
                    </a>
                    {% endif %}
                  </li>
                <li>
                    {% if object_list.has_next %}
                    <a href="?page={{ object_list.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true"><i class="ion-ios-arrow-right"></i> Next</span>
                    </a>
                    {% endif %}
                </li>
                </ul>
            </nav>
        </div>
        <!-- /// -->
      </div>
    </div>
    <br><br>

{% endblock body%} 